### ISSUE TITLE
"This app has crashed"

### ISSUE THREAD

**Issue by Dijker** [MarvinSchenkel/HomeyTwitter#1]
**What is your Homey version (Settings → System)?**
0.8.34 / App v0.0.3

**What did you try to achieve?**
Installed it,  connected with my twitter, but didn't use it really in flows at this moment.

**Please include detailed steps how we can reproduce the issue**
Don't know yet if I can reproduce!

**What was the result?**
Homey Settings / Apps report: "This app has crashed"

**What did you expect as result?**
No Crash ;-)

Any other remarks
Disabled and removed yuor app for the moment as I have to troubleshoot what makes Homey unstable at this moment, 
Don't know if .34 is unstable or the App, or the missing restarts of Homey ;-)

**Comment by MarvinSchenkel** [comment]
That's weird. Twitter has been working without crashes for a while.. I just updated to 0.8.34 last night. I'll try to reproduce!

**Comment by Dijker** [comment]
Don't know what happened then.... 
already weeks working and happy  tweeting from Homey 0.9.3. 
Thanks!
